theme: osuny
_merge: deep
pagination:
  pagerSize: 20
params:
  # RENNES THEME CUSTOM
  custom:
    active_custom_map: true
    is_main: false
    external_logo_link:
      active: true
      url: "https://metropole.rennes.fr"
      title: "Rennes Ville et Métropole"
    search:
      active: true
      url: "https://chercher.metropole.rennes.fr"
    footer_europe: "/assets/images/footer_europe.png"
    footer_europe_link: "https://www.europe-en-france.gouv.fr/"
    footer_europe_alt: "Union Européenne - Unaniezh Europa, l'Europe s'engage en Bretagne, avec le fonds européen de développement régional"
    contact_link: "https://metropole.rennes.fr/contact"
    pages:
      taxonomy_display_as_chip: "rubrique"
    media_econception_link: "https://metropole.rennes.fr/ecoconception/"

  # GLOBAL SETTINGS
  additional_csp: "rennesmetropole.matomo.cloud cdn.matomo.cloud; style-src 'self' 'unsafe-inline';"

  # DESIGN SYSTEM
  logo:
    header: "/assets/images/rennes-ville-metropole_noir.svg"
    footer: "/assets/images/rennes-ville-metropole_blanc.svg"
  menu:
    ecosystem:
      level_2:
        title:
          active: true
    thematic:
      level_2:
        title:
          active: true
  breadcrumb:
    extendable: true
    position: hero-start
  summary:
    position: hero
  search:
    active: false
    positions:
      - custom-menu
  home:
    head:
      title: site # both | page | site
  # We can also specify this options for each sharable Section
  share_links:
    enabled: true
    email: true
    facebook: true
    linkedin: true
    mastodon: false
    telegram: false
    twitter: false
    whatsapp: false

  # SECTIONS
  categories:
    index:
      layout: cards
  pages:
    date_format: "02/01/2006"
    index:
      options:
        categories: true
        image: false
    single:
      taxonomies:
        position: hero

  posts:
    index:
      options:
        categories: true
    single:
      options:
        categories: true
    sitemap:
      ignore_children: true

  events:
    single:
      taxonomies:
        position: hero
    sitemap:
      ignore_children: true

  persons:
    sitemap:
      ignore_children: true

  organizations:
    index:
      options:
        logo: false
    sitemap:
      ignore_children: true
  # BLOCKS

  # IMAGES SIZES
  components:
    lightbox:
      disabled: true
  image_sizes:
    blocks:
      call_to_action:
        mobile: 500
        tablet: 605
        desktop: 768
    sections:
      posts:
        item:
          mobile: 350
          tablet: 800
          desktop: 858
